AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ApplicationName:
    Type: String
    Description: Name of the application. This is consistent across the stacks.
Resources:
    ECRRepository:
        Type: "AWS::ECR::Repository"
        Properties:
            EmptyOnDelete: true
            RepositoryName: !Ref ApplicationName
