AWSTemplateFormatVersion: "2010-09-09"
Resources:
    ECRRepository:
        Type: "AWS::ECR::Repository"
        Properties:
            EmptyOnDelete: true
            RepositoryName: "proper-app-name-repository"
